name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PIP_CONSTRAINT_PATH: "constraint.txt"

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        build_type: [ Debug, Release ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Init
      run: |
        echo 'Cython < 3.0' > ${{ env.PIP_CONSTRAINT_PATH }}
        python3 --version

    - name: MacOS
      if: runner.os == 'MacOS'
      run: |
        which python3
        brew install python3.11
        which python3
        which pip3

    - name: Prepare
      uses: turtlebrowser/get-conan@main
      env:
        PIP_CONSTRAINT: ${{ env.PIP_CONSTRAINT_PATH }}
      with:
        version: 1.59.0

    - name: Install dependencies - Linux
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install -y gcc-13 g++-13 libfmt-dev libglfw3-dev libgtest-dev libgmock-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60 --slave /usr/bin/g++ g++ /usr/bin/g++-13

    - name: Install dependencies - MacOS
      if: runner.os == 'MacOS'
      run: |
        brew install fmt glfw3 googletest

    - name: Install dependencies - Windows
      uses: johnwason/vcpkg-action@v5
      if: runner.os == 'Windows'
      with:
        pkgs: fmt glfw3 gtest
        triplet: x64-windows
        token: ${{ github.token }}

    - name: Build - Linux
      if: runner.os == 'Linux'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DSUPPRESS_COMPILER_WERROR=1
        cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Build - MacOS
      if: runner.os == 'MacOS'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Build - Windows
      if: runner.os == 'Windows'
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

    - name: Unit Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{ matrix.build_type }}
